name: 'Flutter Dependencies Update'
description: 'Get token and update dependencies'
inputs:
  PUB_TOKEN:  # path
    description: 'token to access server'
    required: true
    type: string

runs:
  using: "composite"
  steps: 
    - name: Flutter Clean
        run: rm pubspec.lock; flutter clean
        continue-on-error: true

      - name: Get Dependencies
        run: echo ${{ inputs.PUB_TOKEN }} | dart pub token add https://pub.trii.ws; flutter pub get; flutter pub upgrade